# Generated by Django 3.0.5 on 2020-05-18 12:36

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctorprofileinfo',
            name='available_weekdays',
            field=models.CharField(default='1111100', max_length=8),
        ),
        migrations.AddField(
            model_name='doctorprofileinfo',
            name='end_hour',
            field=models.IntegerField(default=20, validators=[django.core.validators.MaxValueValidator(20), django.core.validators.MinValueValidator(9)]),
        ),
        migrations.AddField(
            model_name='doctorprofileinfo',
            name='start_hour',
            field=models.IntegerField(default=8, validators=[django.core.validators.MaxValueValidator(20), django.core.validators.MinValueValidator(8)]),
        ),
        migrations.AddField(
            model_name='doctorprofileinfo',
            name='visit_duration',
            field=models.FloatField(choices=[(1, 'یک ساعت'), (0.5, 'نیم ساعت'), (0.75, 'سه ربع')], default=0.5),
        ),
    ]
