# Generated by Django 3.0.5 on 2020-04-16 08:25

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20200407_1752'),
    ]

    operations = [
        migrations.CreateModel(
            name='DoctorProfileInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('portfolio_site', models.URLField(blank=True)),
                ('profile_pic', models.ImageField(blank=True, upload_to='profile_pics')),
                ('specialty', models.CharField(blank=True, max_length=254)),
                ('degree', models.CharField(choices=[('دکتری', 'دکتری'), ('کارشناسی', 'کارشناسی'), ('کارشناسی\u200cارشد', 'کارشناسی ارشد'), ('تخصص', 'تخصص'), ('فوق\u200cتخصص', 'فوق تخصص'), ('-', '-')], default='-', max_length=254)),
                ('educational_background', models.CharField(blank=True, max_length=254, null=True)),
                ('score', models.FloatField(blank=True, default=0, null=True, validators=[django.core.validators.MaxValueValidator(5), django.core.validators.MinValueValidator(0)])),
                ('fee', models.FloatField(blank=True, default=0, null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('on_site_fee', models.BooleanField(blank=True, default=False)),
                ('address', models.CharField(max_length=500)),
                ('credit', models.FloatField(blank=True, default=0, null=True, validators=[django.core.validators.MinValueValidator(0)])),
            ],
        ),
        migrations.CreateModel(
            name='PatientProfileInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile_pic', models.ImageField(blank=True, upload_to='profile_pics')),
                ('birthday', models.DateField()),
                ('medical_condition', models.CharField(blank=True, max_length=254, null=True)),
                ('credit', models.FloatField(blank=True, default=0, null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('height', models.FloatField(blank=True, null=True)),
                ('weight', models.FloatField(blank=True, null=True)),
                ('blood_type', models.CharField(blank=True, choices=[('A', 'A'), ('B', 'B'), ('AB', 'AB'), ('O', 'O')], max_length=4, null=True)),
                ('blood_plus_minus', models.CharField(blank=True, choices=[('M', '-'), ('P', '+')], max_length=2, null=True)),
                ('allergies', models.CharField(blank=True, max_length=254, null=True)),
                ('medical_emergency_contact', models.CharField(error_messages={'شماره وارد شده معتبر نیست.': 'incomplete'}, max_length=13, validators=[django.core.validators.RegexValidator('^[0]?9[0-9]{9}$', 'شماره موبایل معتبر وارد کنید')])),
            ],
        ),
        migrations.AddField(
            model_name='user',
            name='family_name',
            field=models.CharField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name='user',
            name='is_doctor',
            field=models.BooleanField(default=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='user',
            name='name',
            field=models.CharField(blank=True, default='arad', max_length=254),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='UserProfileInfo',
        ),
        migrations.AddField(
            model_name='patientprofileinfo',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='doctorprofileinfo',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
