# Generated by Django 3.0.5 on 2020-04-07 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_userprofileinfo'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofileinfo',
            name='height',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userprofileinfo',
            name='weight',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
