# Generated by Django 3.0.5 on 2020-05-24 19:02

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('doctor_calendar', '0003_auto_20200523_2203'),
        ('prescription', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='prescriptions',
            unique_together={('doctor', 'patient', 'appointment')},
        ),
    ]
